server:
  port: 8005
spring:
  datasource:
    url:  jdbc:mysql://221.181.73.31:8009/star_pomelo?characterEncoding=UTF-8
    username: root
    password: stardb
    driver-class-name: com.mysql.jdbc.Driver
  jpa.database: MYSQL
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update

