server:
  port: 8004
spring:
  application:
    name: login
  datasource:
      #本地url  jdbc:mysql://127.0.0.1:3306/star_polemo?characterEncoding=UTF-8&useSSL=true
      url:  jdbc:mysql://221.181.73.31:8009/star_pomelo?characterEncoding=UTF-8
      username: root
      password: stardb
      driver-class-name:  com.mysql.jdbc.Driver
  jpa.database: MYSQL
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
  #redis配置
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 100



